version: "3.9" # optional since v1.27.0
services:
  #  frontend:
  #    image: keropon48/springtaskapp-front
  #    ports:
  #      - "443:8043"
  backend:
    container_name: "taskapp-back"
    x-aws-pull_credentials: arn:aws:secretsmanager:ap-northeast-1:030073904594:secret:dockerhubAccessToken-O31KAg
    image: keropon48/springtaskapp:v1.1.14
    ports:
      - "8080:8080"
