version: "3.9" # optional since v1.27.0
services:
  #  frontend:
  #    image: keropon48/springtaskapp-front
  #    ports:
  #      - "443:8043"
  backend:
    container_name: "taskapp-back"
    image: keropon48/springtaskapp:v1.1.0
    ports:
      - "8080:8080"
