#ワークフロー名を「Java CI with Maven」に設定
name: Deploy

#masterブランチへのpush時にこのワークフローを実行するよう指定
on:
  push:
    branches: [ master ]

#以下JOB
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Create context
      run: |
        cat ~/.aws/credentials 
        docker context create ecs ecscontext --profile default

    - name: Deploy for ECS
      run: |
        docker context use ecscontext
        docker compose up
