name: Update packages

on:
  repository_dispatch:
    types: [update-pkgs]
  workflow_dispatch:
    inputs:
      part:
        description: 'front or back'
        required: true
        default: ''
      imagetag:
        description: 'deploy app version'
        required: true
        default: ''

jobs:
  update-pkgs:
    env:
      ENV: prod

    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set env
        if: ${{ github.event.client_payload.imagetag != null }}
        run: echo "RELEASE_VERSION=/${{ github.event.client_payload.imagetag }}" | awk -F'[/]' '{print $1, $4}' | sed 's/ //g' >> $GITHUB_ENV

      # dcoker imageの修正
      # 別リポジトリから更新するver (https://github.com/Yumapon/SpringTaskApp)
      #参考：https://mikefarah.gitbook.io/yq/commands/evaluate
      - name: chage docker image(frontend) by auto
        uses: mikefarah/yq@master
        if: ${{ github.event.client_payload.part == 'front' }} 
        with:
          cmd: yq e '.services.frontend.image = "keropon48/springtaskappfront:${{ env.RELEASE_VERSION }}"' -i docker-compose.yaml

      - name: chage docker image(backend) by auto
        uses: mikefarah/yq@master
        if: ${{ github.event.client_payload.part == 'back' }}
        with:
          cmd: yq e '.services.backend.image = "keropon48/springtaskapp:${{ env.RELEASE_VERSION }}"' -i docker-compose.yaml

      # 直接Actionから更新するver
      # 参考：
      - name: chage docker image(frontend) by semiauto
        uses: mikefarah/yq@master
        if: ${{ github.event.inputs.part == 'front' }}
        with:
          cmd: yq e '.services.frontend.image = "keropon48/springtaskappfront:${{ github.event.inputs.imagetag }}"' -i docker-compose.yaml

      - name: chage docker image(backend) by semiauto
        uses: mikefarah/yq@master
        if: ${{ github.event.inputs.part == 'back' }}
        with:
          cmd: yq e '.services.backend.image = "keropon48/springtaskapp:${{ github.event.inputs.imagetag }}"' -i docker-compose.yaml

      # PRの発行
      #参考：https://github.com/peter-evans/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          commit-message: |
            [${{ env.ENV }}] update container image
          committer: GitHub <noreply@github.com>  
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: create-pull-request/release/${{ env.ENV }}
          base: master
          delete-branch: true
          title: |
            [${{ env.ENV }}] Update Backend or Front Container Image
          body: |
            [${{ env.ENV }}] Update Backend or Front Container Image
          labels: |
            update container image
            ${{ env.ENV }} release

      #　確認用
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

          